apiVersion: apps/v1
kind: Deployment
metadata:
  name: logoutput-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      volumes: # Define volume
        - name: shared-image
          emptyDir: {}
      containers:
        - name: logoutput
          image: pekkamattinen/logoutput:07
          volumeMounts:
            - name: shared-image
              mountPath: /opt/app/files
        - name: logreader
          image: pekkamattinen/logreader
          volumeMounts:
            - name: shared-image
              mountPath: /opt/app/files