apiVersion: v1
data:
    POSTGRES_DB: ENC[AES256_GCM,data:HJMo7mKSFA==,iv:rwIGz7H7nDw7liZ4DXK40v9TzU6tMGBj8zYUkUj2LiA=,tag:Rz9Slndcf/HvL6lXFGzJjA==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:COR0ww==,iv:MhS1GJ2TBLzmACOLNTwJ1m3JTMZLNtuyEQNxR9zoblA=,tag:tBn7NkxNlWq/FSSGuuXbUg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:rE3yKQ==,iv:hZnDUzJNeSBzQrjDQGT0mTod+WAfQtJNmcjNmDH6uuo=,tag:6QP15aH1fqKp7jsEte78nA==,type:str]
    DB_DSN: ENC[AES256_GCM,data:yZjWs2XfZZ1jUP6F2MrD2rJBMbQQlghy2a++9zPMiu5fIj3ZrgS70XGL0W0vyFj6vF1ZA9nsH3/LevGs4c11rQl3Slv5tA==,iv:SEvgfFSjY035gejQOBBypF8ZHbMdcpjJ2FXtTAZjk1A=,tag:QUll6fvtKt4WSwEWoABF/A==,type:str]
kind: ConfigMap
metadata:
    name: project-map
    namespace: project
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1rndm72df6ge3e5ku6r5k0s9dsj6px0ayrnexysaxazu4mp6lrepqlqjpap
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzS2tvN1M4dm1UZkM3S2Fw
            YWxycnZZRlIwd0xJWXd1OCtRQ3prVTdaZlJJCmpwbmtURDJ1TnBWdnFKWVVIUEpS
            dUxzczExZzlDWGU5ZTBLeFVJMzd6S00KLS0tIEpMaUx6TWxHSnR5eDRsa3FINWUr
            alhsdm42ZDdzTzhZd0dQL2dORTdFSk0KvScVOvaYU3RXGd5LdOO6ehFaJpfyP8/a
            bnz3kSx7tzbythhou+Nwgi5B37XRwTkw8R4fkAdCQ0BQlXlDBnFAbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-05T18:05:31Z"
    mac: ENC[AES256_GCM,data:wWm8ooLeZAQ/4VqY2WN8XhcyTblMh6wNlF6mKFbcwIvBnlF/8M6y/cpxBD5KjQdb+cEpmgFIfwV1vO+s4WJjVI0/tzq17pXQ7iAip5G+2wmi0L0BCDilOhbEBEftN9b1zA9NvDw0dGu5Glc015/JHy4zYQxKGIQ2XG2J0qkZ+vg=,iv:8Zm5UFfcDp8PGycpfwP58ASSVhF0tD7JxcwYx6yMRh0=,tag:pr32+r7gYCqUJalmYmdkPw==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.7.3
