apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logoutput-claim
  namespace: logoutput
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
